title: The pulse of the language services industry.
description: Daily translation and localization news capturing the trends, innovations, and movements shaping the language services industry. Stay tuned to what’s driving global communication.
url: "https://locreport.com"
lang: "en"
author: "LocReport"
og_locale: "en_US"
twitter_username: "locreport"
social_image: "/assets/images/logolocreport.png"
